### ISSUE TITLE
gpu install

### ISSUE THREAD

**Issue by bowen-cau** [AI-sandbox/snputils#1]
Mac OS 15.1 , Apple M2 Ultra

$ pip install snputils[gpu]

Error: 
INFO: pip is looking at multiple versions of snputils[gpu] to determine which version is compatible with other requirements. This could take a while.
Collecting snputils[gpu]
  Downloading snputils-0.1.1-py3-none-any.whl.metadata (3.4 kB)
  Downloading snputils-0.1.0-py3-none-any.whl.metadata (2.7 kB)
WARNING: snputils 0.1.0 does not provide the extra 'gpu'
ERROR: Cannot install snputils[gpu]==0.1.0, snputils[gpu]==0.1.1 and snputils[gpu]==0.2.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    snputils[gpu] 0.2.0 depends on torch; extra == "gpu"
    snputils[gpu] 0.1.1 depends on torch; extra == "gpu"
    snputils[gpu] 0.1.0 depends on torch

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

however, 
$ pip install snputils
seemed to complete install

**Comment by salcc** [comment]
Just in case anyone else encounters this problem: This issue appears to be caused by PyTorch not yet having support for Python 3.13 on macOS (see https://github.com/pytorch/pytorch/issues/130249). Using Python 3.12 on macOS or Python 3.13 on Linux works for me.
